org: null

app: null

service: authentication-lambda

plugins:
  - serverless-offline

custom:
  iam:
    role: arn:aws:iam::658623738065:role/LabRole
    disableRoleCreation: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  cfnRole: arn:aws:iam::658623738065:role/LabRole
  timeout: 30
  iam:
    role: arn:aws:iam::658623738065:role/LabRole

package: 
  exclude: 
    - terraform/**

functions:
  api:
    handler: dist/main.authUser