org: null

app: null

service: afluga-auth

plugins:
  - serverless-offline

custom:
  iam:
    role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/LabRole
    disableRoleCreation: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  cfnRole: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/LabRole
  timeout: 30
  iam:
    role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/LabRole

functions:
  api:
    handler: handler.handler
