org: null

app: null

service: afluga-auth

plugins:
  - serverless-offline

custom:
  iam:
    role: arn:aws:iam::658623738065:role/LabRole
    disableRoleCreation: true

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  cfnRole: arn:aws:iam::658623738065:role/LabRole
  timeout: 30
  iam:
    role: arn:aws:iam::658623738065:role/LabRole

functions:
  api:
    handler: dist/main.authUser
    environment:
        REGION: ${env:AWS_REGION}
        ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
        SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
        SESSION_TOKEN: ${env:AWS_SESSION_TOKEN}
        COGNITO_USER_POOL_ID: ${env:AWS_COGNITO_USER_POOL_ID}
        COGNITO_TEMPORARY_PASSWORD: ${env:AWS_COGNITO_TEMPORARY_PASSWORD}
        COGNITO_CLIENT_AUTH_FLOW: ${env:AWS_COGNITO_CLIENT_AUTH_FLOW}
        COGNITO_CLIENT_ID: ${env:AWS_COGNITO_CLIENT_ID}
        COGNITO_CLIENT_SECRET: ${env:AWS_COGNITO_CLIENT_SECRET}
        COGNITO_DEFAULT_USER_GROUP: ${env:AWS_COGNITO_DEFAULT_USER_GROUP}
