name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Install Serverless CLI
      run: sudo npm install -g serverless --unsafe-perm=true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy with Serverless
      run: serverless deploy
      env:
        SERVERLESS_PLATFORM_VENDOR: aws
        SERVERLESS_DISABLE_AUTO_UPDATE: true
        SLS_DISABLE_AUTO_UPDATE: true
        SERVERLESS_PLATFORM_DISABLE: true
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_COGNITO_TEMPORARY_PASSWORD: ${{ secrets.AWS_COGNITO_TEMPORARY_PASSWORD }}
        AWS_COGNITO_USER_POOL_ID: ${{ secrets.AWS_COGNITO_USER_POOL_ID }}
        AWS_COGNITO_DEFAULT_USER_GROUP: ${{ secrets.AWS_COGNITO_DEFAULT_USER_GROUP }}
        AWS_COGNITO_CLIENT_AUTH_FLOW: ${{ secrets.AWS_COGNITO_CLIENT_AUTH_FLOW }}
        AWS_COGNITO_CLIENT_ID: ${{ secrets.AWS_COGNITO_CLIENT_ID }}
        AWS_COGNITO_CLIENT_SECRET: ${{ secrets.AWS_COGNITO_CLIENT_SECRET }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
